[package]
name = "toma"
version = "0.1.0"
edition = "2024"
authors = ["TodoEsVerso <todoesverso@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/todoesverso/toma"
homepage = "https://github.com/todoesverso/toma"
documentation = "https://docs.rs/toma"
keywords = ["server", "cli", "tool", "http", "web"]
categories = ["command-line-utilities"]


[[bin]]
name = "toma"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
futures-util = "0.3.34"
http-body-util = "0.1.4"
hyper = { version = "1.11.0", features = ["full"] }
hyper-util = { version = "0.1.20", features = ["full"] }
moka = { version = "0.12.16", features = ["future"] }
serde = { version = "1.0.229", features = ["derive"] }
serde-saphyr = "1.0.1"
tokio = { version = "1.53.1", features = ["full"] }
tokio-util = { version = "0.7.19", features = ["io"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
